on: [pull_request, push]
permissions:
  actions: write
  attestations: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  models: read
  pages: write
  pull-requests: write
  repository-projects: write
  statuses: write
  security-events: write
  id-token: write
  contents: write
  packages: write
jobs:
 linux:
    uses: minecraft-linux/appimage-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
 macOS:
    uses: minecraft-linux/macos-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
